package com.formatic.core.builder;

import com.formatic.core.annotation.handler.FormFieldAnnotationHandler;
import com.formatic.core.form.BytecodeAccessor;
import com.formatic.core.form.CachedFormMetadata;
import com.formatic.core.form.FormFieldMetadata;
import com.formatic.core.form.ReflectionFallback;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.modifier.Visibility;

import net.bytebuddy.implementation.FixedValue;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

public class BytecodeFormFieldMetadataBuilder implements FormFieldMetadataBuilder {

    private static final Logger log = LoggerFactory.getLogger(BytecodeFormFieldMetadataBuilder.class);

    private final List<FormFieldAnnotationHandler<?>> handlers;
    private final Map<Class<?>, CachedFormMetadata> cache = new ConcurrentHashMap<>();
    private final ByteBuddy byteBuddy;

    public BytecodeFormFieldMetadataBuilder(List<FormFieldAnnotationHandler<?>> handlers) {
        this.handlers = handlers;
        this.byteBuddy = new ByteBuddy();
        log.info("BytecodeFormFieldMetadataBuilder initialized with {} handlers", handlers.size());
    }

    /**
     *
     * Main entry point - identical to the reflection version
     */
    public List<FormFieldMetadata> buildMetadata(Class<?> clazz) {
        CachedFormMetadata cached = cache.computeIfAbsent(clazz, this::generateBytecodeAccessor);
        return cached.getMetadata();
    }

    /**
     * Generates a bytecode accessor optimized for the class
     * Processus:
     * Analyze class
     * Generate dynamically a java class with metadata
     */
    private CachedFormMetadata generateBytecodeAccessor(Class<?> clazz) {
        long startTime = System.nanoTime();

        try {
            List<FormFieldMetadata> metadata = analyzeWithReflection(clazz);

            //Create unique class name
            String accessorClassName = String.format(
                    "%s$FormaticAccessor$%08x",
                    clazz.getName(),
                    System.identityHashCode(clazz)
            );

            //ByteCode generation
            //Class loaded once and reuse
            Class<?> accessorClass = byteBuddy
                    .subclass(Object.class)
                    .name(accessorClassName)
                    //Defines a method that returns metadata
                    .defineMethod("getMetadata", List.class, Visibility.PUBLIC)
                    .intercept(FixedValue.reference(metadata))
                    .make()
                    .load(clazz.getClassLoader())
                    .getLoaded();

            //Create a instance
            Object accessor = accessorClass.getDeclaredConstructor().newInstance();

            long duration = System.nanoTime() - startTime;
            log.info("Generated bytecode accessor for {} in {:.2f}ms - {} fields",
                    clazz.getSimpleName(), duration / 1_000_000.0, metadata.size());

            return new BytecodeAccessor(metadata, accessor);

        } catch (Exception e) {
            log.error("Failed to generate bytecode for {}, using fallback", clazz.getSimpleName(), e);
            //Fallback: only reflexion version
            return new ReflectionFallback(analyzeWithReflection(clazz));
        }
    }

    /**
     * Analyze class with reflection
     */
    private List<FormFieldMetadata> analyzeWithReflection(Class<?> clazz) {
        List<FormFieldMetadata> result = new ArrayList<>();

        for (Field field : clazz.getDeclaredFields()) {
            handlers.stream()
                    .filter(h -> h.supports(field))
                    .findFirst()
                    .ifPresent(handler -> {
                        FormFieldMetadata m = handler.handle(field);
                        if (m != null) result.add(m);
                    });
        }

        return result.stream()
                .sorted(Comparator.comparingInt((FormFieldMetadata m) ->
                        m.getOrder() == 0 ? Integer.MAX_VALUE : m.getOrder()))
                .collect(Collectors.toList());
    }

}
