package com.formatic.core.form;

import com.formatic.core.annotation.handler.FormFieldAnnotationHandler;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.modifier.Visibility;

import net.bytebuddy.implementation.FixedValue;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

public class BytecodeFormFieldMetadataBuilder {

    private static final Logger log = LoggerFactory.getLogger(BytecodeFormFieldMetadataBuilder.class);

    private final List<FormFieldAnnotationHandler<?>> handlers;
    private final Map<Class<?>, CachedFormMetadata> cache = new ConcurrentHashMap<>();
    private final ByteBuddy byteBuddy;

    public BytecodeFormFieldMetadataBuilder(List<FormFieldAnnotationHandler<?>> handlers) {
        this.handlers = handlers;
        this.byteBuddy = new ByteBuddy();
        log.info("BytecodeFormFieldMetadataBuilder initialized with {} handlers", handlers.size());
    }

    /**
     * Point d'entrée principal - identique à la version réflexion
     */
    public List<FormFieldMetadata> buildMetadata(Class<?> clazz) {
        CachedFormMetadata cached = cache.computeIfAbsent(clazz, this::generateBytecodeAccessor);
        return cached.getMetadata();
    }

    /**
     * Génère un accesseur bytecode optimisé pour la classe
     *
     * Processus:
     * 1. Analyse la classe avec réflexion (UNE SEULE FOIS)
     * 2. Génère une classe Java dynamique contenant les métadonnées
     * 3. Les accès suivants lisent directement la constante
     */
    private CachedFormMetadata generateBytecodeAccessor(Class<?> clazz) {
        long startTime = System.nanoTime();

        try {
            List<FormFieldMetadata> metadata = analyzeWithReflection(clazz);

            //Création du nom de la classe unique
            String accessorClassName = String.format(
                    "%s$FormaticAccessor$%08x",
                    clazz.getName(),
                    System.identityHashCode(clazz)
            );

            //Génération de bytecode avec ByteBuddy
            //Cette classe sera chargée une seule fois et réutilisée
            Class<?> accessorClass = byteBuddy
                    .subclass(Object.class)
                    .name(accessorClassName)
                    // Définit une méthode qui retourne les métadonnées
                    .defineMethod("getMetadata", List.class, Visibility.PUBLIC)
                    .intercept(FixedValue.reference(metadata))
                    .make()
                    .load(clazz.getClassLoader())
                    .getLoaded();

            //Crée une instance de l'accesseur
            Object accessor = accessorClass.getDeclaredConstructor().newInstance();

            long duration = System.nanoTime() - startTime;
            log.info("Generated bytecode accessor for {} in {:.2f}ms - {} fields",
                    clazz.getSimpleName(), duration / 1_000_000.0, metadata.size());

            return new BytecodeAccessor(metadata, accessor);

        } catch (Exception e) {
            log.error("Failed to generate bytecode for {}, using fallback", clazz.getSimpleName(), e);
            //Fallback: version réflexion simple
            return new ReflectionFallback(analyzeWithReflection(clazz));
        }
    }

    /**
     * Analyse une classe avec réflexion
     */
    private List<FormFieldMetadata> analyzeWithReflection(Class<?> clazz) {
        List<FormFieldMetadata> result = new ArrayList<>();

        for (Field field : clazz.getDeclaredFields()) {
            handlers.stream()
                    .filter(h -> h.supports(field))
                    .findFirst()
                    .ifPresent(handler -> {
                        FormFieldMetadata m = handler.handle(field);
                        if (m != null) result.add(m);
                    });
        }

        return result.stream()
                .sorted(Comparator.comparingInt((FormFieldMetadata m) ->
                        m.getOrder() == 0 ? Integer.MAX_VALUE : m.getOrder()))
                .collect(Collectors.toList());
    }

}
